server:
  port: 3344
spring:
  #rabbitmq相关配置
  rabbitmq:
    host: 119.3.160.28
    port: 5672
    username: admin
    password: admin
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/lxl2018/springcloud-config # git仓库的地址
          search-paths: / # git仓库地址下的相对地址，可以配置多个，用,分割。
          username: 15810140695 #Git仓库用户名
          password: lxl552211 #Git仓库密码

#服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka

##rabbitmq相关配置,暴露bus刷新配置的端点
management:
  endpoints: #暴露bus刷新配置的端点
    web:
      exposure:
        include: 'bus-refresh'