server:
  port: 8401

spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        #Nacos服务注册中心地址
        server-addr: localhost:8848
    sentinel:
      transport:
        #配置Sentinel dashboard地址
        dashboard: localhost:8080
        #默认8719端口，假如被占用会自动从8719开始依次+1扫描,直至找到未被占用的端口
        #它监控8401【微服务】的同时
        #8719是http通信服务【sentinel后台监控服务】
        #还有8080【sentinel前台展示服务】交互数据
        #将监控的数据在dashboard上展现
        port: 8719

management:
  endpoints:
    web:
      exposure:
        include: '*'