server:
  port: 8004
#服务别名----注册zookeeper到注册中心名称
spring:
  application:
    name: cloud-provider-payment
  cloud:
    zookeeper:
      connect-string: 119.3.160.28:2181
      discovery:
        # 创建zookeeper根目录名称, 默认是 /service
        root: /payment